#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  6 16:08:13 2023

@author: dai
"""

import numpy as np
import pandas as pd
from scipy.stats import ttest_ind
from scipy.stats import probplob
import matplotlib.pyplot as plt
import pylab
import seaborn as sns
